services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: hackaton_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
